// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: market_data.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 틱 데이터 (체결)
type TickData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`                             // 종목 코드 (예: 005930)
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`                             // 현재가
	Volume        int64                  `protobuf:"varint,3,opt,name=volume,proto3" json:"volume,omitempty"`                            // 체결량
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                      // 체결 시간 (Unix nanoseconds)
	Change        float64                `protobuf:"fixed64,5,opt,name=change,proto3" json:"change,omitempty"`                           // 전일 대비 등락
	ChangeRate    float64                `protobuf:"fixed64,6,opt,name=change_rate,json=changeRate,proto3" json:"change_rate,omitempty"` // 등락률
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickData) Reset() {
	*x = TickData{}
	mi := &file_market_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickData) ProtoMessage() {}

func (x *TickData) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickData.ProtoReflect.Descriptor instead.
func (*TickData) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{0}
}

func (x *TickData) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *TickData) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TickData) GetVolume() int64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *TickData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TickData) GetChange() float64 {
	if x != nil {
		return x.Change
	}
	return 0
}

func (x *TickData) GetChangeRate() float64 {
	if x != nil {
		return x.ChangeRate
	}
	return 0
}

// 호가 데이터 (OrderBook)
type OrderBook struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Bids          []*Level               `protobuf:"bytes,2,rep,name=bids,proto3" json:"bids,omitempty"` // 매수 호가
	Asks          []*Level               `protobuf:"bytes,3,rep,name=asks,proto3" json:"asks,omitempty"` // 매도 호가
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBook) Reset() {
	*x = OrderBook{}
	mi := &file_market_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBook) ProtoMessage() {}

func (x *OrderBook) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBook.ProtoReflect.Descriptor instead.
func (*OrderBook) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{1}
}

func (x *OrderBook) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OrderBook) GetBids() []*Level {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *OrderBook) GetAsks() []*Level {
	if x != nil {
		return x.Asks
	}
	return nil
}

func (x *OrderBook) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 호가 레벨
type Level struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         float64                `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Level) Reset() {
	*x = Level{}
	mi := &file_market_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Level) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Level) ProtoMessage() {}

func (x *Level) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Level.ProtoReflect.Descriptor instead.
func (*Level) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{2}
}

func (x *Level) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Level) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

var File_market_data_proto protoreflect.FileDescriptor

const file_market_data_proto_rawDesc = "" +
	"\n" +
	"\x11market_data.proto\x12\vmarket_data\"\xa7\x01\n" +
	"\bTickData\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x16\n" +
	"\x06volume\x18\x03 \x01(\x03R\x06volume\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06change\x18\x05 \x01(\x01R\x06change\x12\x1f\n" +
	"\vchange_rate\x18\x06 \x01(\x01R\n" +
	"changeRate\"\x91\x01\n" +
	"\tOrderBook\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12&\n" +
	"\x04bids\x18\x02 \x03(\v2\x12.market_data.LevelR\x04bids\x12&\n" +
	"\x04asks\x18\x03 \x03(\v2\x12.market_data.LevelR\x04asks\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"9\n" +
	"\x05Level\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x03R\bquantityB-Z+github.com/jjongkwann/aipx/shared/go/pkg/pbb\x06proto3"

var (
	file_market_data_proto_rawDescOnce sync.Once
	file_market_data_proto_rawDescData []byte
)

func file_market_data_proto_rawDescGZIP() []byte {
	file_market_data_proto_rawDescOnce.Do(func() {
		file_market_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_market_data_proto_rawDesc), len(file_market_data_proto_rawDesc)))
	})
	return file_market_data_proto_rawDescData
}

var file_market_data_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_market_data_proto_goTypes = []any{
	(*TickData)(nil),  // 0: market_data.TickData
	(*OrderBook)(nil), // 1: market_data.OrderBook
	(*Level)(nil),     // 2: market_data.Level
}
var file_market_data_proto_depIdxs = []int32{
	2, // 0: market_data.OrderBook.bids:type_name -> market_data.Level
	2, // 1: market_data.OrderBook.asks:type_name -> market_data.Level
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_market_data_proto_init() }
func file_market_data_proto_init() {
	if File_market_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_market_data_proto_rawDesc), len(file_market_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_market_data_proto_goTypes,
		DependencyIndexes: file_market_data_proto_depIdxs,
		MessageInfos:      file_market_data_proto_msgTypes,
	}.Build()
	File_market_data_proto = out.File
	file_market_data_proto_goTypes = nil
	file_market_data_proto_depIdxs = nil
}
